name: Auto-PR
on:
  push:
    branches: ['feature']

jobs:
  pull-request:
    name: PR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "develop"
        base: feature
        pr_title: "Auto PR from feature to develop"
        pr_body: "ðŸ‘‘ *An automated PR*"
        pr_reviewer: "kingdonb"
        github_token: ${{ secrets.GITHUB_TOKEN }}
